version: '3'

services:
  back:
    image: node:16
    working_dir: /opt/nest-lessons/app
    command: ["yarn", "start:dev"]
    env_file:
      - ./.env.example
    depends_on:
      postgres:
        condition: service_healthy
    ports:
      - "3000:3000"
    volumes:
      - "./:/opt/nest-lessons/app"

  postgres:
    image: postgres:13
    container_name: postgres
    healthcheck:
      test: pg_isready -U oksana -d avito
      interval: 10s
      timeout: 3s
      retries: 3
    restart: always
    environment:
      - POSTGRES_PASSWORD=academy
      - POSTGRES_DB=avito
      - POSTGRES_USER=oksana
